name: My First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, world!"
      - name: Execute Multi-Line Scripts
        run: |
          pwd
          ls -al
      - name: Print Farewell
        run: echo "Goodbye, cruel world!"
